autoload -U compinit && compinit
autoload -U promptinit && promptinit

bindkey -e

setopt correct_all
zstyle ':completion:*' menu select

export CLICOLOR=1
alias ll='ls -lh'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='fd -H'
export FZF_CTRL_T_COMMAND='fd -H'
export FZF_DEFAULT_OPTS="-e --multi --layout=reverse --preview='bat --color=always --tabs=2 --style=plain --theme=Monokai\ Extended {}'"
export FZF_CTRL_R_OPTS="-e --layout=reverse"
_fzf_compgen_path() {
  fd -H . "$1"
}
_fzf_compgen_dir() {
  fd -H --type d . "$1"
}

source ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/themes/powerlevel10k/powerlevel10k.zsh-theme
source ~/.dotfiles/zsh/p10k.zsh

[ -e ~/.zshrc.local ] && source ~/.zshrc.local
