setopt correct_all
autoload -U compinit && compinit
if [[ "$OSTYPE" == (darwin|freebsd)* ]]; then
  alias ls='ls -G'
elif [[ "$OSTYPE" == linux* ]]; then
  alias ls='ls --color=tty'
fi
alias ll='ls -lh'
source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh/themes/slimline/slimline.zsh
SLIMLINE_USER_HOST_INFO_FORMAT="%F{green}|user|%F{white}@%F{cyan}|host|%f"
SLIMLINE_USER_HOST_INFO_ROOT_FORMAT="%F{red}|user|%F{white}@%F{cyan}|host|%f"
SLIMLINE_SYMBOL_WORKING_FORMAT="%F{red}➜%f"
SLIMLINE_SYMBOL_READY_FORMAT="%F{white}➜%f"
SLIMLINE_MAX_EXEC_TIME=2
[ -e ~/.zshrc.local ] && source ~/.zshrc.local
